//Products
export const GET_PRODUCT_DATA = 'GET_PRODUCT_DATA';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_HOT_SELLER_PRODUCT = 'GET_HOT_SELLER_PRODUCT';
export const GET_PRODUCT_DATA_PAGING = 'GET_PRODUCT_DATA_PAGING';
export const GET_RELATED_PRODUCT = 'GET_RELATED_PRODUCT';

//Categories
export const GET_CATEGORIES_DATA = 'GET_CATEGORIES_DATA';

//Carts
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const LOAD_PRODUCT_IN_CART = 'LOAD_PRODUCT_IN_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const POST_CART = 'POST_CART';
export const DELETE_CART = 'DELETE_CART';

//Account
export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT';
export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT';
export const LOAD_ACCOUNT = 'LOAD_ACCOUNT';


//Brand
export const GET_BRAND_DATA = 'GET_BRAND_DATA';

//Comment
export const GET_COMMENT_DATA = 'GET_COMMENT_DATA';
export const GET_LENGTH = 'GET_LENGTH';
export const ADD_COMMENT = 'ADD_COMMENT';
export const GET_RATING = 'GET_RATING';
export const GET_COMMENT_USER = 'GET_COMMENT_USER';

//Option
export const GET_OPTION_DATA = 'GET_OPTION_DATA';
export const GET_OPTION_VALUE_DATA = 'GET_OPTION_VALUE_DATA';
export const GET_OPTION = 'GET_OPTION';
export const REMOVE_OPTION = 'REMOVE_OPTION';